version: '2.6'
volumes:
  tfdata: {}
services:
  terraform:
    image: hashicorp/terraform:1.6.5
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - TF_DATA_DIR=/terraform-data
      - TF_WORKSPACE=$ENVIRONMENT
    volumes:
      - tfdata:/terraform-data
      - $PWD/infra:/infra
    working_dir: /infra
  terraform-init:
    extends: terraform
    entrypoint: sh
    command:
      - -c
      - |
        cat >/backend.tfvars <<-EOF
        bucket = "$TERRAFORM_STATE_S3_BUCKET"
        key = "$TERRAFORM_STATE_S3_KEY"
        region = "$AWS_REGION"
        EOF
        terraform init -backend-config=/backend.tfvars
  terraform-plan:
    extends: terraform
    command:
      - plan
      - -input=false
  terraform-apply:
    extends: terraform
    command:
      - apply
      - -auto-approve
  terraform-output:
    extends: terraform
    entrypoint:
      - terraform
      - output
      - -raw
  terraform-destroy:
    extends: terraform
    command:
      - destroy
      - -auto-approve
