version: '2.6'
services:
  frontend:
    build:
      dockerfile: frontend.Dockerfile
      context: .
    ports:
      - 8080:8080
  backend:
    build:
      dockerfile: backend.Dockerfile
      context: .
  unit-tests-frontend:
    extends: frontend
    entrypoint: go
    command:
      - test
      - app/frontend_test.go
  unit-tests-backend:
    extends: backend
    entrypoint: go
    command:
      - test
      - app/backend_test.go
  integration-tests-frontend:
    extends: frontend
    entrypoint: go
    environment:
      INTEGRATION: true
    command:
      - test
      - app/frontend_test.go
