version: '2.6'
volumes:
  gocache: {}
  gomod: {}
services:
  frontend:
    build:
      context: .
      args:
        app: frontend
    environment:
      BACKEND_URL: http://backend:8080
    ports:
      - 8080:8080
  backend:
    build:
      context: .
      args:
        app: backend
  unit-tests-frontend:
    image: golang:1.21-alpine
    volumes:
      - $PWD/app/frontend:/go/github.com/carlosonunez/example-app/src
      - gocache:/root/.cache/go-build
      - gomod:/go/pkg/mod
    working_dir: /go/github.com/carlosonunez/example-app/src
    entrypoint: [ "go" ]
    command:
      - test
      - -failfast
      - .
  unit-tests-backend:
    image: golang:1.21-alpine
    volumes:
      - $PWD/app/backend:/go/github.com/carlosonunez/example-app/src
      - gocache:/root/.cache/go-build
      - gomod:/go/pkg/mod
    working_dir: /go/github.com/carlosonunez/example-app/src
    entrypoint: [ "go" ]
    command:
      - test
      - -failfast
      - .
  integration-tests-frontend:
    extends: frontend
    entrypoint: go
    environment:
      INTEGRATION: true
    command:
      - test
      - app/frontend_test.go
