version: '2.6'
volumes:
  gocache: {}
  gomod: {}
services:
  frontend:
    build:
      context: .
      args:
        app: frontend
    environment:
      BACKEND_URL: http://localhost:8081
      DISABLE_CORS_THIS_IS_UNSAFE: "true"
    ports:
      - 8080:8080
  backend:
    build:
      context: .
      args:
        app: backend
    environment:
      DISABLE_CORS_THIS_IS_UNSAFE: "true"
    ports:
      - 8081:8080
  unit-tests-frontend:
    image: golang:1.21-alpine
    volumes:
      - $PWD/app/frontend:/go/github.com/carlosonunez/example-app/src
      - gocache:/root/.cache/go-build
      - gomod:/go/pkg/mod
    working_dir: /go/github.com/carlosonunez/example-app/src
    entrypoint: [ "go" ]
    command:
      - test
      - -failfast
      - .
  unit-tests-backend:
    image: golang:1.21-alpine
    volumes:
      - $PWD/app/backend:/go/github.com/carlosonunez/example-app/src
      - gocache:/root/.cache/go-build
      - gomod:/go/pkg/mod
    working_dir: /go/github.com/carlosonunez/example-app/src
    entrypoint: [ "go" ]
    command:
      - test
      - -failfast
      - .
  integration-tests:
    image: golang:1.21-alpine
    volumes:
      - $PWD/app/frontend:/go/github.com/carlosonunez/example-app/src
      - gocache:/root/.cache/go-build
      - gomod:/go/pkg/mod
    working_dir: /go/github.com/carlosonunez/example-app/src
    entrypoint: go
    environment:
      - INTEGRATION=true
      - FRONTEND_URL=http://$FQDN
      - BACKEND_URL=http://$FQDN/backend
    extra_hosts:
      - "$FQDN:$IP"
    command:
      - test
      - ./integration_test.go
