apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Release.Name }}.{{ .Values.ingress.hostName }}
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend-svc
                port:
                  name: http
          - path: '/backend'
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend-svc
                port:
                  name: http
