apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
    component: frontend
  ports:
    - name: http
      targetPort: 8080
      port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
    component: backend
  ports:
    - name: http
      targetPort: 8080
      port: 8080
